---
# tasks file for erlang
- name: debian | Repository - add the GPG key
  ansible.builtin.apt_key:
    url: '{{ erlang_ppa_key }}'
    id: '{{ erlang_ppa_key_id }}'
    state: present
  when: erlang_ppa_key != None

- name: debian | Add repository to install Erlang from
  ansible.builtin.apt_repository:
    repo: '{{ erlang_ppa_repo }}'
    update_cache: yes
  when: erlang_ppa_repo != None

- name: debian | Install packages
  ansible.builtin.apt:
    pkg: '{{ item }}'
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items: '{{ erlang_packages }}'
